// <auto-generated />
using System;
using FutureHub.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FutureHub.Web.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20251123195243_RemoveMissaoId")]
    partial class RemoveMissaoId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutureHub.Web.Models.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UK_AREA_NOME");

                    b.ToTable("T_FH_AREAS", (string)null);
                });

            modelBuilder.Entity("FutureHub.Web.Models.Avaliacao", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_AVALIACAO");

                    b.Property<string>("IdeiaId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("IDEIA_ID");

                    b.Property<int>("Nota")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTA");

                    b.HasKey("Id");

                    b.HasIndex("DataAvaliacao")
                        .HasDatabaseName("IDX_AVALIACAO_DATA");

                    b.HasIndex("IdeiaId")
                        .HasDatabaseName("IDX_AVALIACAO_IDEIA");

                    b.ToTable("T_FH_AVALIACOES", (string)null);
                });

            modelBuilder.Entity("FutureHub.Web.Models.Ideia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AutorId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("AUTOR_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<double>("MediaNotas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("BINARY_DOUBLE")
                        .HasDefaultValue(0.0)
                        .HasColumnName("MEDIA_NOTAS");

                    b.Property<string>("MissaoId")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("MISSAO_ID");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR2(160)")
                        .HasColumnName("TITULO");

                    b.Property<int>("TotalAvaliacoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("TOTAL_AVALIACOES");

                    b.HasKey("Id");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("IDX_IDEIA_AUTOR");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IDX_IDEIA_CREATED");

                    b.HasIndex("MediaNotas")
                        .HasDatabaseName("IDX_IDEIA_MEDIA");

                    b.ToTable("T_FH_IDEIAS", (string)null);
                });

            modelBuilder.Entity("FutureHub.Web.Models.Ranking", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR2(7)")
                        .HasColumnName("PERIODO");

                    b.Property<int>("PontuacaoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("PONTUACAO_TOTAL");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("Periodo")
                        .HasDatabaseName("IDX_RANKING_PERIODO");

                    b.HasIndex("PontuacaoTotal")
                        .HasDatabaseName("IDX_RANKING_PONTUACAO");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IDX_RANKING_USUARIO");

                    b.HasIndex("UsuarioId", "Periodo")
                        .IsUnique()
                        .HasDatabaseName("UK_RANKING_USUARIO_PERIODO");

                    b.ToTable("T_FH_RANKINGS", (string)null);
                });

            modelBuilder.Entity("FutureHub.Web.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AreaInteresseId")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("AREA_INTERESSE_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<int>("Pontos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("PONTOS");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasDefaultValue("ROLE_USER")
                        .HasColumnName("ROLE");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA_HASH");

                    b.HasKey("Id");

                    b.HasIndex("AreaInteresseId")
                        .HasDatabaseName("IDX_USUARIO_AREA");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_USUARIO_EMAIL");

                    b.ToTable("T_FH_USUARIOS", (string)null);
                });

            modelBuilder.Entity("FutureHub.Web.Models.Avaliacao", b =>
                {
                    b.HasOne("FutureHub.Web.Models.Ideia", "Ideia")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AVALIACAO_IDEIA");

                    b.Navigation("Ideia");
                });

            modelBuilder.Entity("FutureHub.Web.Models.Ideia", b =>
                {
                    b.HasOne("FutureHub.Web.Models.Usuario", "Autor")
                        .WithMany("Ideias")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IDEIA_AUTOR");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("FutureHub.Web.Models.Ranking", b =>
                {
                    b.HasOne("FutureHub.Web.Models.Usuario", "Usuario")
                        .WithMany("Rankings")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RANKING_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FutureHub.Web.Models.Usuario", b =>
                {
                    b.HasOne("FutureHub.Web.Models.Area", "AreaInteresse")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaInteresseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_USUARIO_AREA");

                    b.Navigation("AreaInteresse");
                });

            modelBuilder.Entity("FutureHub.Web.Models.Area", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FutureHub.Web.Models.Ideia", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("FutureHub.Web.Models.Usuario", b =>
                {
                    b.Navigation("Ideias");

                    b.Navigation("Rankings");
                });
#pragma warning restore 612, 618
        }
    }
}
